In [1]:
import numpy as np

# Part 1

## create a list

In [2]:
list = [4,8,2,10,6]
arr = np.array(list)
print (arr)

[ 4  8  2 10  6]


#### Create a numpy array with shape (100,) where all the values are one.

In [3]:
zero_array = np.zeros((100,))
print (zero_array)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0.]


##### Create a numpy array with shape (10,14) where all the values are zero and save it as arr.

In [4]:
arr = np.zeros((10,14))
print (arr)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


#### 5.Type the following code into a cell.

In [5]:
print(arr)
print(arr + 1)
print(arr)
arr += 1
print(arr)
arr -= 1
print(arr)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]
[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]
[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 

##### Which of these operations changed the underlying values in the array? Answer in the cell below using the markdown.

arr += 1 changed the array and arr -=1 changed the actual values held in variable arr

##### 7

In [6]:
arr[3,5]=8
arr[3,8]=8
print(arr)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 8. 0. 0. 8. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


In [7]:
arr[6,4:10]=2
print(arr)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 8. 0. 0. 8. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 2. 2. 2. 2. 2. 2. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


In [8]:
arr1 =arr[3:7,4:10]
print(arr1)

[[0. 8. 0. 0. 8. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [2. 2. 2. 2. 2. 2.]]


# part 2

In [9]:
print(np.nonzero(arr))
print(np.nonzero(arr1))

(array([3, 3, 6, 6, 6, 6, 6, 6], dtype=int64), array([5, 8, 4, 5, 6, 7, 8, 9], dtype=int64))


##### 2.1 non-zero shows you the indexes of where a non-zero value is. so as long as there is anything besides a 0 it will show  you where that value is

2.2  find the indices of an array, where a condition is True

2.3

In [14]:
arr = np.zeros((10,14))
arr[0,8]=7
arr[1,8]=7
arr[2,2]=7
arr[3,2]=7
arr[4,2]=7
arr[5,2]=7
arr[6,2]=7
arr[7,2]=7
print(arr)
print(np.nonzero(arr))

[[0. 0. 0. 0. 0. 0. 0. 0. 7. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 7. 0. 0. 0. 0. 0.]
 [0. 0. 7. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 7. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 7. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 7. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 7. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 7. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]
(array([0, 1, 2, 3, 4, 5, 6, 7], dtype=int64), array([8, 8, 2, 2, 2, 2, 2, 2], dtype=int64))


2.4 Returns an array with axes transposed
2.5 it will change the order and the shape of the array
this prediction was somewhat correct i did not predict how it would change the values but i did get the reshaping correct.

In [16]:
long_arr = np.array([[0,0,0,1,1,1],[4,4,4,5,5,5]])
print(long_arr)
print(np.transpose(long_arr))
print(long_arr.T)

[[0 0 0 1 1 1]
 [4 4 4 5 5 5]]
[[0 4]
 [0 4]
 [0 4]
 [1 5]
 [1 5]
 [1 5]]
[[0 4]
 [0 4]
 [0 4]
 [1 5]
 [1 5]
 [1 5]]


## part 4

In [17]:
import pandas as pd
import numpy as np
import matplotlib as ml


In [20]:
pres_csv = pd.read_csv("1976-2020-president.csv")
print(pres_csv)

      year    state state_po  state_fips  state_cen  state_ic        office  \
0     1976  ALABAMA       AL           1         63        41  US PRESIDENT   
1     1976  ALABAMA       AL           1         63        41  US PRESIDENT   
2     1976  ALABAMA       AL           1         63        41  US PRESIDENT   
3     1976  ALABAMA       AL           1         63        41  US PRESIDENT   
4     1976  ALABAMA       AL           1         63        41  US PRESIDENT   
...    ...      ...      ...         ...        ...       ...           ...   
4282  2020  WYOMING       WY          56         83        68  US PRESIDENT   
4283  2020  WYOMING       WY          56         83        68  US PRESIDENT   
4284  2020  WYOMING       WY          56         83        68  US PRESIDENT   
4285  2020  WYOMING       WY          56         83        68  US PRESIDENT   
4286  2020  WYOMING       WY          56         83        68  US PRESIDENT   

                    candidate              party_de

the canidate votes are in the 10th column
the difference between the columns is that party_detailed has specific party details and party simplified has only 4 options Democrat, republican, libertarian or other

In [27]:
num_pres = pd.Series(pres_csv['candidate']).unique()
print (num_pres)

['CARTER, JIMMY' 'FORD, GERALD' 'MADDOX, LESTER' 'BUBAR, BENJAMIN ""BEN""'
 'HALL, GUS' 'MACBRIDE, ROGER' nan 'MCCARTHY, EUGENE ""GENE""'
 'CAMEJO, PETER' 'ANDERSON, THOMAS J.' 'WRIGHT, MARGARET'
 'LAROUCHE, LYNDON, JR.' 'SCATTERING' 'OTHER' 'JULIUS ""JULES"", LEVIN'
 'ZEIDLER, FRANK' 'REAGAN, RONALD' 'ANDERSON, JOHN B.' 'RARICK, JOHN'
 'CLARK, EDWARD ""ED""' 'DEBERRY, CLIFTON' 'MCREYNOLDS, DAVID'
 'COMMONER, BARRY' 'GRISWOLD, DEIRDRE' 'SMITH, MAUREEN' 'PULLEY, ANDREW'
 'GREAVES, PERCY L, JR.' 'SHELTON, FRANK, JR.' 'MCCORMACK, ELLEN'
 'LYNEN, KURT' 'GAHRES, WILLIAM ""BILL""' 'WENDELKEN, MARTIN E.'
 'MCLAIN, HARLEY' 'CONGRESS, RICHARD' 'MONDALE, WALTER' 'BERGLAND, DAVID'
 'RICHARDS, BOB' 'MASON, MELVIN' 'SERRETTE, DENNIS' 'JOHNSON, SONIA'
 'DODGE, EARL' 'LOWERY, ARTHUR' 'DENNIS, DELMAR' 'HOLMES, LARRY'
 'WINN, EDWARD' 'BAKER, GERALD' 'BUSH, GEORGE H.W.' 'DUKAKIS, MICHAEL'
 'PAUL, RONALD ""RON""' 'FULANI, LENORA' 'KENOYER, WILLA'
 'WARREN, JAMES ""MAC""' 'DUKE, DAVID' 'HERER, JACK' 'HERB

In [32]:
print(len(num_pres))

271


In [43]:
pres_csv.loc[pres_csv['year']==2020]

year    state state_po  state_fips  state_cen  state_ic        office  \
3740  2020  ALABAMA       AL           1         63        41  US PRESIDENT   
3741  2020  ALABAMA       AL           1         63        41  US PRESIDENT   
3742  2020  ALABAMA       AL           1         63        41  US PRESIDENT   
3743  2020  ALABAMA       AL           1         63        41  US PRESIDENT   
3744  2020   ALASKA       AK           2         94        81  US PRESIDENT   
...    ...      ...      ...         ...        ...       ...           ...   
4282  2020  WYOMING       WY          56         83        68  US PRESIDENT   
4283  2020  WYOMING       WY          56         83        68  US PRESIDENT   
4284  2020  WYOMING       WY          56         83        68  US PRESIDENT   
4285  2020  WYOMING       WY          56         83        68  US PRESIDENT   
4286  2020  WYOMING       WY          56         83        68  US PRESIDENT   

                candidate party_detailed writein  candidatevotes  totalvotes  \
3740  BIDEN, JOSEPH R. JR       DEMOCRAT   False          849624     2323282   
3741     TRUMP, DONALD J.     REPUBLICAN   False         1441170     2323282   
3742        JORGENSEN, JO    LIBERTARIAN   False           25176     2323282   
3743                  NaN            NaN    True            7312     2323282   
3744  BIDEN, JOSEPH R. JR       DEMOCRAT   False          153778      359530   
...                   ...            ...     ...             ...         ...   
4282        JORGENSEN, JO    LIBERTARIAN   False            5768      278503   
4283        PIERCE, BROCK    INDEPENDENT   False            2208      278503   
4284                  NaN            NaN    True            1739      278503   
4285            OVERVOTES            NaN   False             279      278503   
4286           UNDERVOTES            NaN   False            1459      278503   

       version  notes party_simplified  
3740  20210113    NaN         DEMOCRAT  
3741  20210113    NaN       REPUBLICAN  
3742  20210113    NaN      LIBERTARIAN  
3743  20210113    NaN            OTHER  
3744  20210113    NaN         DEMOCRAT  
...        ...    ...              ...  
4282  20210113    NaN      LIBERTARIAN  
4283  20210113    NaN            OTHER  
4284  20210113    NaN            OTHER  
4285  20210113    NaN            OTHER  
4286  20210113    NaN            OTHER  

[547 rows x 15 columns]

In [49]:
pres2020 = pres_csv.loc[pres_csv['year']==2020]
print(pres2020['candidatevotes'].sum()[''])

158528503


In [52]:
total_votes = pres_csv.groupby('year').sum('totalvotes')
print (total_votes)

      state_fips  state_cen  state_ic  candidatevotes  totalvotes  \
year                                                                
1976        9839      17287     12678        81601344   605944064   
1980       10607      18842     13958        86496851   663902096   
1984        9523      16831     12494        92654861   609936856   
1988        8322      15021     11187        91586825   537099170   
1992       10699      20090     14984       104599780   770486377   
1996       10415      20328     15054        96389818   728343795   
2000       10704      20217     15029       105593982   783441739   
2004        9054      17355     12905       122349450   768259747   
2008       10030      19141     14177       131419253   992684830   
2012        9036      17403     12939       129139997   879479158   
2016        9692      18977     14218       136787187   941573717   
2020       14760      28570     20806       158528503  1865852281   

          version  notes  
year  